### ISSUE TITLE
Keep the symmetry of the encoder and decoder blocks

### ISSUE THREAD

**Issue by YilinLiu97** [Ziyan-Huang/AdwU-Net#3]
Hi, Thanks for open-sourcing your great work. I'm wondering, how do you handle the symmetry of the searched encoder and decoder blocks? 

Let's say, for depth search in stage 3, two AwBlocks are kept, i.e., a1 = a3 = 0, a2 > 0.  then the corresponding decoder AwBlock on stage 3 should also keep 2 AwBlocks, right? Does that essentially mean, we just need to search for the encoder only? Thanks!

**Comment by Ziyan-Huang** [comment]
Hi Yilin,

In our paper, we do not restrict the encoder and decoder to keep symmetry. All AdwBlocks are searched independently and simultaneously. So in your example, though the searched depth in stage 3 is 2 in the encoder, the depth in the corresponding decoder is still probably between 1 to 3.

**Comment by YilinLiu97** [comment]
Hi Ziyan, Thank you for the quick reply. I'm wondering, how does skip connection work then, if it's not symmetrical? Is it because, only the last one of the 3 AdwBlocks contains the max-pooling/strided convolutions, and the skip connection is built on that block only?

**Comment by Ziyan-Huang** [comment]
Hi Yilin, 

The skip connection is only from the last block in the encoder to the first block in the corresponding decoder. It is ok regardless of the internal number of convolutions in encoder and decoder blocks and whether they are symmetric or not.

Also, the strided convolution is conducted on the **first** AdwBlock of the encoder (except for the first stage) for downsampling.

**Comment by YilinLiu97** [comment]
Got it! Thank you so much.
